# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build and publish image to Functions

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  Build_frontend:
    name: Build frontend using Vue.
    runs-on: ubuntu-latest
    env: 
      node-version: 13.10.1
    defaults:
      run:
        working-directory: Azure/Vue/weatherdisp
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.node-version }}
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Build
      run: yarn run build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: vue
        path: Azure/Vue/weatherdisp/dist/index.html
  Build_runtime:
    name: Build functions.
    runs-on: ubuntu-latest
    env:
      dotnet: 3.1.100
    defaults:
      run:
        working-directory: Azure/Functions/WeatherDisp
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnet }}
      - name: Create Dist
        run: mkdir -p dist
      - name: Build and publish
        run: dotnet publish *.csproj --output dist && cp dist/bin/runtimes/linux-x64/native/Magick.Native-Q8-x64.dll.so dist/bin/Magick.Native-Q8-x64.dll.so
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: functions
          path: Azure/Functions/WeatherDisp/dist     
  Image_Build_and_Publish:
    runs-on: ubuntu-latest
    needs: [Build_frontend, Build_runtime]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download frontend artifact
        uses: actions/download-artifact@v2
        with:
          name: vue
          path: images/dist
      - name: Download runtime artifact
        uses: actions/download-artifact@v2
        with:
          name: functions
          path: images
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: images
      - name: build image and push to github package registory
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{env.GITHUB_REPOSITORY}}/weatherdisp
          registry: ocker.pkg.github.com
          tags: latest
          tag_with_ref: true
          tag_with_sha: true
          path: images
